apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rwu3tumwv-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rwu3tumwv-python 
  name: rwu3tumwv-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rwu3tumwv-python 
